# Generated by Django 5.1.6 on 2025-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbook",
            name="edition",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
