# Generated by Django 5.1.6 on 2025-03-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia_book", "0002_alter_textbook_edition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textbook",
            name="edition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
